---

- name: Install necessary packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vagrant
      - virtualbox
      - ansible
    become: true

- name: Provision VM using Vagrant
  hosts: all
  gather_facts: false
  tasks:
    - name: Execute Vagrant up
      command: vagrant up
      args:
        chdir: ./Vagrant
      become: false