---
- name: Run Docker Compose
  hosts: control
  gather_facts: no
  tasks:
    - name: Include Docker Compose based on choice
      command: docker-compose up -d
      args:
        chdir: /vagrant
      #when: deployment_choice.user_input == 'docker'
