Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
  
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
  
    config.vm.define "control", primary: true do |node|
      node.vm.box = "envimation/ubuntu-xenial"
      node.vm.hostname = "control"
      node.vm.network "private_network", ip: "192.168.56.10"
      node.vm.provider :virtualbox do |vb|
        vb.name = "Control Station"
        vb.cpus = 1
      end

      node.vm.provision :shell, :inline => <<-SCRIPT
        if [ ! -f "/home/vagrant/.ssh/id_rsa" ]; then
          ssh-keygen -t rsa -b 2048 -N "" -f /home/vagrant/.ssh/id_rsa
        fi
        cp /home/vagrant/.ssh/id_rsa.pub /vagrant/control.pub
        cat << 'SSHEOF' > /home/vagrant/.ssh/config
        Host *
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
        SSHEOF
  
        chown -R vagrant:vagrant /home/vagrant/.ssh/
        sudo apt update -y
        sudo apt upgrade -y
        # Add any additional provisioning commands here
      SCRIPT
    end

    config.vm.define "oc-srv-01", primary: true do |node|
      node.vm.box = "envimation/ubuntu-xenial"
      node.vm.hostname = "oc-srv-01"
      node.vm.network "private_network", ip: "192.168.56.20"
      node.vm.provider :virtualbox do |vb|
        vb.name = "OwnCloud"
        vb.cpus = 1
      end

      node.vm.provision :shell, :inline => <<-SHELL
      cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end

    config.vm.define "infdb-srv-01", primary: true do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = 'infdb-srv-01'
      node.vm.network "private_network", ip: "192.168.56.30"
      node.vm.provider :virtualbox do |vb|
        vb.name = "InfluxDB"
        vb.cpus = 1
        # Add the port forwarding configuration for port 8086
        vb.customize ["modifyvm", :id, "--natpf1", "influxdb,tcp,,8086,,8086"]
      end

      node.vm.provision :shell, :inline => <<-SHELL
      cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys
      
      sudo apt update
      SHELL
    end

    config.vm.define "grf-srv-01", primary: true do |node|
      node.vm.box = "envimation/ubuntu-xenial"
      node.vm.hostname = 'grf-srv-01'
      node.vm.network "private_network", ip: "192.168.56.40"
      node.vm.provider :virtualbox do |vb|
        vb.name = "Grafana"
        vb.cpus = 1
      end
      
      node.vm.provision :shell, :inline => <<-SHELL
      cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end

    config.vm.define "tlg-srv-01", primary: true do |node|
      node.vm.box = "envimation/ubuntu-xenial"
      node.vm.hostname = 'tlg-srv-01'
      node.vm.network "private_network", ip: "192.168.56.50"
      node.vm.provider :virtualbox do |vb|
        vb.name = "Telegraf"
        vb.cpus = 1
      end
      
      node.vm.provision :shell, :inline => <<-SHELL
      cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end


  end
  