Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
  
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
  
    config.vm.define "control", primary: true do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "control"
      node.vm.network "private_network", ip: "192.168.50.10"
      node.vm.provision :shell, :inline => << -SCRIPT
        if [ ! -f "/home/vagrant/.ssh/id_rsa" ]; then
          ssh-keygen -t rsa -b 2048 -N "" -f /home/vagrant/.ssh/id_rsa
        fi
        cp /home/vagrant/.ssh/id_rsa.pub /vagrant/control.pub
        cat << 'SSHEOF' > /home/vagrant/.ssh/config
        Host *
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
        SSHEOF
  
        chown -R vagrant:vagrant /home/vagrant/.ssh/
        sudo apt update -y
        sudo apt upgrade -y
        # Add any additional provisioning commands here
      SCRIPT
    end

    config.vm.define "oc_srv_01", primary: true do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "oc_srv_01"
      node.vm.network "private_network", ip: "192.168.50.20"
      node.vm.provision :shell, :inline 'cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys'
    end

    config.vm.define "infdb_srv_01", primary: true do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "infdb_srv_01"
      node.vm.network "private_network", ip: "192.168.50.30"
      node.vm.provision :shell, :inline 'cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys'
    end

    config.vm.define "grf_srv_01", primary: true do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "grf_srv_01"
      node.vm.network "private_network", ip: "192.168.50.30"
      node.vm.provision :shell, :inline 'cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys'
    end

    config.vm.define "tlg_srv_01", primary: true do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "tlg_srv_01"
      node.vm.network "private_network", ip: "192.168.50.30"
      node.vm.provision :shell, :inline 'cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys'
    end


  end
  