Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true #
    
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
  
    config.vm.define "control", primary: true do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "control"
      node.vm.network "private_network", ip: "192.168.33.10"
      node.vm.provision :shell, :inline << 'EOF'
    if [ ! -f "/home/vagrant/.ssh/id_rsa" ]; then
        ssh-keygen -t rsa -b 2048 -N "" -f /home/vagrant/.ssh/id_rsa
    fi
        cp /home/vagrant/.ssh/id_rsa.pub /vagrant/control.pub
        cat << 'SSHEOF' > /home/vagrant/.ssh/config
        Host *
            StricktHostKeyChecking no
            UserKnownHostFile=/dev/null
        SSHEOF

        chown -R vagrant:vagrant /home/vagrant/.ssh/
        sudo apt update -y
        sudo apt ugrade -y
        # Add any additional provisioning commands here
      EOF
    end
end