---
- name: Configure and Install ownCloud
  hosts: oc-srv-01
  become: yes

  tasks:
  - name: Add PHP repository
    apt_repository:
      repo: ppa:ondrej/php
      state: present
    become: yes
  #   register: task_results

  # - name: print task task_results
  #   debug:
  #     var: task_results

  - name: Update and upgrade packages
    apt:
      update_cache: yes
      upgrade: yes
    become: yes

  - name: Install required packages
    apt:
      name: "{{ item }}"
      state: present
    become: yes
    loop:
      - php7.4
      - php7.4-fpm 
      - php7.4-intl
      - php7.4-mysql
      - php7.4-mbstring
      - php7.4-imagick
      - php7.4-igbinary
      - php7.4-gmp
      - php7.4-bcmath
      - php7.4-curl
      - php7.4-gd 
      - php7.4-zip
      - php7.4-imap
      - php7.4-ldap
      - php7.4-bz2
      - php7.4-ssh2
      - php7.4-common
      - php7.4-json
      - php7.4-xml
      - php7.4-dev
      - php7.4-apcu
      - php7.4-redis
      - libsmbclient-dev
      - php-pear
      - php-phpseclib
      - smbclient
      - redis-server
      - php-redis
      - python3-mysqldb
      - unzip
      - openssl
      - rsync
      - imagemagick
      - libapache2-mod-php7.4
      - apache2
      - mariadb-server
      - mariadb-client
      - python3-mysql.connector
      - smbclient

  - name: Set PHP alternatives
    command: "sudo update-alternatives --set {{ item }}"
    loop:
      - "php /usr/bin/php7.4"
      - "phar /usr/bin/phar7.4"
      - "phar.phar /usr/bin/phar.phar7.4"
      - "phpize /usr/bin/phpize7.4"
      - "php-config /usr/bin/php-config7.4"

  - name: Create smbclient.ini
    block:
      - name: Create file 
        shell: | 
          touch "/etc/php/7.4/mods-available/smbclient.ini"
        become: yes

      - name: Append file
        lineinfile:
          path: "/etc/php/7.4/mods-available/smbclient.ini"
          line: "extension=smbclient.so"
        become: yes

  - name: Enable smbclient module
    command: "sudo phpenmod smbclient"

  - name: Install php7.4-fpm on Ubuntu
    become: yes
    apt:
      name: php7.4-fpm
      state: present
    environment:
      DEBIAN_FRONTEND: noninteractive
      UCF_FORCE_CONFFNEW: "true"

  - name: Restart Apache
    service:
      name: apache2
      state: restarted
    become: yes

  - name: Create dbadmin user
    mysql_user:
      name: dbadmin
      password: dbpassword
      priv: '*.*:ALL'
      host: localhost
      state: present
    become: true

  - name: Create owncloud database
    mysql_db:
      name: owncloud
      state: present
    become: true

  - name: Create ocuser user
    mysql_user:
      name: ocuser
      password: ocpassword
      priv: '*.*:ALL'
      host: localhost
      state: present
    become: true

  - name: Grant privileges on owncloud database to ocuser
    mysql_user:
      name: ocuser
      password: ocpassword
      priv: 'owncloud.*:ALL'
      host: localhost
      state: present
    become: true

  - name: Exit MySQL prompt
    command: mysql -u root -e "exit"
    ignore_errors: yes
    become: yes

  - name: Download and verify ownCloud
    become: yes
    shell: |
      wget https://download.owncloud.com/server/stable/owncloud-complete-latest.tar.bz2
      wget https://download.owncloud.com/server/stable/owncloud-complete-latest.tar.bz2.sha256
      sha256sum -c owncloud-complete-latest.tar.bz2.sha256 < owncloud-complete-latest.tar.bz2
      tar -xjvf owncloud-complete-latest.tar.bz2
      chown -R www-data:www-data owncloud
      ln -s /var/www/owncloud/occ occ
      chown -R www-data:www-data occ
      mv owncloud-complete-latest.tar.bz2 /home/vagrant/
      touch /etc/apache2/sites-available/owncloud.conf 
      ln -s /etc/apache2/sites-available/owncloud.conf /etc/apache2/sites-enabled/owncloud.conf
    args:
      chdir: "/var/www/"

  - name: Update owncloud.conf
    blockinfile:
      path: /etc/apache2/sites-available/owncloud.conf
      content: |
        Alias /owncloud "/var/www/owncloud/"

        <Directory /var/www/owncloud/>
          Options +FollowSymlinks
          AllowOverride All

        <IfModule mod_dav.c>
          Dav off
        </IfModule>
        </Directory>
    become: yes

  - name: Restart Apache service
    service:
      name: apache2
      state: restarted
    become: yes

  - name: Install smbclient
    package:
      name: smbclient
      state: present
    become: yes

  - name: Enable smbclient PHP extension
    lineinfile:
      dest: "/etc/php/7.4/cli/php.ini"
      regexp: '^;?extension=smbclient\.so$'
      line: 'extension=smbclient.so'
    become: yes

  - name: Run occ maintenance:install
    args:
      chdir: "/var/www/owncloud/"
    shell: |
      sudo -u www-data php occ maintenance:install \
        --database "mysql" \
        --database-name "owncloud" \
        --database-user "ocuser" \
        --database-pass "ocpassword" \
        --admin-user "ocuser" \
        --admin-pass "ocpassword"
    become: yes
    ignore_errors: yes
    tags:
      - occ user

  - name: Update config.php
    replace:
      path: /var/www/owncloud/config/config.php
      regexp: "'localhost'"
      replace: "'oc-srv-01'"
    become: yes
    ignore_errors: yes
    tags:
      - config_php

  - name: Repair config.php
    shell: |
      sed -i '14{s/oc-srv-01/localhost/}' /var/www/owncloud/config/config.php
    become: yes

  - name: Update trusted domains with 'pms18.ddns.net' in OwnCloud config
    become: yes
    lineinfile:
      path: /var/www/owncloud/config/config.php
      regexp: "^(\\s*'trusted_domains' =>\\s*\\()"
      line: "        1 => 'pms18.ddns.net',"
      insertafter: "0 => 'oc-srv-01',"

  - name: Restart Apache service
    service:
      name: apache2
      state: restarted
    become: yes