Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
  
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false # Enable the VBoxGuestAdditions plugin
      config.vbguest.no_remote = false # This prevents remote installation, speeding up provisioning
    end

    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
  
    config.vm.define "oc-srv-01", override: true do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = "oc-srv-01"
      node.vm.network "private_network", ip: "192.168.56.20"
      node.vm.provider :virtualbox do |vb|
        vb.name = "OwnCloud"
        vb.cpus = 1
      #node.vm.provision :shell, inline: 'cat /vagrant/control_external.pub >> /home/vagrant/.ssh/authorized_keys'
      end

      node.vm.provision :shell, :inline => <<-SHELL
      cat /vagrant/pms18_hosts >> /etc/hosts
      SHELL
    end

    config.vm.define "infdb-srv-01", override: true, primary: true do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = 'infdb-srv-01'
      node.vm.network "private_network", ip: "192.168.56.30"
      node.vm.provider :virtualbox do |vb|
        vb.name = "InfluxDB"
        vb.cpus = 1
        # Add the port forwarding configuration for port 8086
        vb.customize ["modifyvm", :id, "--natpf1", "influxdb,tcp,,8086,,8086"]
      end

      node.vm.provision :shell, :inline => <<-SHELL
      cat /vagrant/control_external.pub >> /home/vagrant/.ssh/authorized_keys
      cat /vagrant/pms18_hosts >> /etc/hosts
      sudo apt update
      SHELL
    end

    config.vm.define "grf-srv-01", override: true do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = 'grf-srv-01'
      node.vm.network "private_network", ip: "192.168.56.40"
      node.vm.provider :virtualbox do |vb|
        vb.name = "Grafana"
        vb.cpus = 1
      end
      
      node.vm.provision :shell, :inline => <<-SHELL
      cat /vagrant/control_external.pub >> /home/vagrant/.ssh/authorized_keys
      cat /vagrant/pms18_hosts >> /etc/hosts
      SHELL
    end

    config.vm.define "tlg-srv-01", override: true do |node|
      #node.vm.box = "envimation/ubuntu-xenial"
      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = 'tlg-srv-01'
      node.vm.network "private_network", ip: "192.168.56.50"
      node.vm.provider :virtualbox do |vb|
        vb.name = "Telegraf"
        vb.cpus = 1
      end
      
      node.vm.provision :shell, :inline => <<-SHELL
      cat /vagrant/control_external.pub >> /home/vagrant/.ssh/authorized_keys
      cat /vagrant/pms18_hosts >> /etc/hosts

      SHELL
    end


  end
  